pipeline_type: flux
torch_dtype: bfloat16
device: cuda

model_configs:
  - model_id: "Qwen/Qwen2.5-VL-7B-Instruct"
  - model_id: "stepfun-ai/Step1X-Edit"
    origin_file_pattern: "step1x-edit-i1258.safetensors"
  - model_id: "stepfun-ai/Step1X-Edit"
    origin_file_pattern: "vae.safetensors"

# Test configuration
model_dir: "models/train/Step1X-Edit_lora-rank32-1e4-wd0"
model_name: "step-2000.safetensors"
output_dir: "test_outputs/Step1X-edit-rank32-1e4-wd002"
data_dir: "data/example_image_dataset"

