name: webapp
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - streamlit>=1.31.0
  - pillow>=10.0.0
  - pytorch
  - torchvision
  - numpy
  - einops
  - fire
  - jpeg
  - pip
  - pip:
    - streamlit-scroll-to-top
    - transformers[torch,sentencepiece]>=4.31.0
    - torch
    - safetensors
    - invisible-watermark
    - sentencepiece
    - accelerate
    - -e ../pix2pix/flux 